### ISSUE TITLE
Issue during pod install

### ISSUE THREAD

**Issue by leemcarthur** [lucasharding/antenna#2]
Everything was going well with the installation instructions. When I come to this item:

"Then run the following to download and setup the project.
- bundle exec pod install"

This is the output I get:

`
-> Pod installation complete! There are 6 dependencies from the Podfile and 7 total pods installed.

[!] The `antenna-tvos-extension [Debug]` target overrides the `ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES` build setting defined in `Pods/Target Support Files/Pods-antenna-tvos-extension/Pods-antenna-tvos-extension.debug.xcconfig'. This can lead to problems with the CocoaPods installation
    - Use the `$(inherited)` flag, or
    - Remove the build settings from the target.

[!] The `antenna-tvos-extension [Release]` target overrides the `ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES` build setting defined in `Pods/Target Support Files/Pods-antenna-tvos-extension/Pods-antenna-tvos-extension.release.xcconfig'. This can lead to problems with the CocoaPods installation
    - Use the `$(inherited)` flag, or
    - Remove the build settings from the target.

[!] The `antenna-tvos [Debug]` target overrides the `ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES` build setting defined in `Pods/Target Support Files/Pods-antenna-tvos/Pods-antenna-tvos.debug.xcconfig'. This can lead to problems with the CocoaPods installation
    - Use the `$(inherited)` flag, or
    - Remove the build settings from the target.

[!] The `antenna-tvos [Release]` target overrides the `ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES` build setting defined in `Pods/Target Support Files/Pods-antenna-tvos/Pods-antenna-tvos.release.xcconfig'. This can lead to problems with the CocoaPods installation
    - Use the `$(inherited)` flag, or
    - Remove the build settings from the target.`

I am not sure if this is going to cause issues down the line, but I wanted to bring it to your attention.

**Comment by leemcarthur** [comment]
I *think* the issue I noted above has reared its head. It's either that, or I don't know what I am doing (80% chance of that). When I try and build the app, it comes up with a whole host of errors, some of which indicate an issue with the pod installation. Take a look:

![screen shot 2016-11-16 at 9 38 40 pm](https://cloud.githubusercontent.com/assets/23512888/20373048/db73112a-ac45-11e6-80fe-7549a87b7836.png)

**Comment by lucasharding** [comment]
I don't think the two are related (I have the first warnings as well). But as for the errors, apparently the solution is to delete the Pod files and redo.

1. Delete Podfile.lock
2. Delete Pods folder
3. Run `bundle exec pod install`
4. Open antenna.xcworkspace
5. Run `Product > Clean`
6. Try and build again

**Comment by leemcarthur** [comment]
Yep - that worked! This is awesome! Thanks! 

(I also changed all the com.lucasharding references to my own tied to my own AppIDs, AppGroups etc - but I assume most people will figure that out.)

**Comment by lucasharding** [comment]
Ahh, thanks. I forgot to put that in the README.
