### ISSUE TITLE
Not streaming video

### ISSUE THREAD

**Issue by Ylinen** [lucasharding/antenna#3]
For some reason, I am not able to play the video either live or recorded now.  Just get spinning wheel.  The GUIDE downloads.  I am logged in. Have the latest Apple TV OS.

**Comment by chriszielinski** [comment]
Weird. Streaming it live works fine for me. Can you stream from USTVnow.com on a computer? Just want to ensure it's not your account that's giving us trouble—I suspect it is. You don't actually have to be logged in/authenticated to retrieve the guide.

**Comment by Ylinen** [comment]
Chris;
Thanks for responding.  Now,  LIVE channels work but recordings just get the Spinning wheel.  This is only on Apple TV.  Works fine when I stream in a Chrome Browser on my PC for recordings and live TV.

I side loaded the IPA.  Not Xcode build.

**Comment by chriszielinski** [comment]
Ah, I see. Is this a recent bug? Meaning, has it worked before? If so, can you recall any recent changes to the Apple TV? (e.g. TVos update) 

Unfortunately, I don't have the ability to record shows since I'm not paying for that package, so it may be difficult for me to fix the problem. Nonetheless, I'll try my best.

**Comment by Ylinen** [comment]
Chris;
I don't know.  I just started using your APP.  We live in the Mountain in Western North Carolina.  Have a new wireless wifi service that is fast enough to now stream.  So I started looking for options to get cable and broadcast.  Can't receive OTA and of course no streaming have broadcast yet.

I am on Apple tvOS 10.1.  If you send me the USTVNOW link to join,  I can do that on another account and get you 4 hours of DVR to do testing.  We can PM addresses/links.

Thanks for trying to fix this.  Don't know if I am the only one or just the one using DVR.

The live seems intermittent.  At first it didn't work after trying to play a DVR show.  Then after a while and leaving the APP and coming back, I was able to watch LIVE, but never DVR.

**Comment by Ylinen** [comment]
Chris;
Have been using the APP for a little while.  It is a good design, worthy of effort.  The DVR functionality does not work.  When you select a DVR recording; you just get a spinning wheel.  It is consistent with all recordings.  There must be some difference in the files (DVR vs LIVE).  Probably a very simple fix.  I am not a coder so don't have knowledge to do the debug.

Would like to know if it is just me or all DVR users.  Kind of surprised others have not reported it.

**Comment by lucasharding** [comment]
Sorry, wasn't able to investigate until now. If you update to [this release](https://github.com/lucasharding/antenna/releases/tag/v1.0.1) streaming and DVR playback should be fixed.

**Comment by Ylinen** [comment]
Lucas;
Thanks so much for fixing this issue.  Working great for me now.  You are the best.  My wife will love it.
