### ISSUE TITLE
Swift Complier Error with 1.01

### ISSUE THREAD

**Issue by leemcarthur** [lucasharding/antenna#5]
Hi Lucas/All

After getting the buffering issue with 1.0, I finally decided to upgrade to 1.01 as per the instructions. I am all set to build, but this is the error I get with Product > Build:

![screen shot 2017-04-26 at 11 34 31 pm](https://cloud.githubusercontent.com/assets/23512888/25465557/520b6f14-2ad9-11e7-9c91-6a44b8a140e0.png)

Any ideas?

**Comment by lucasharding** [comment]
Should compile now. It was just an old line of code that no longer actually did anything. It must have started failing in the newest version of Xcode.
