### ISSUE TITLE
New channels

### ISSUE THREAD

**Issue by nigelsmith75** [lucasharding/antenna#6]
USTV Now has added new channels and removed some others. Can we get channel icons for the new channels?
CNN, Cartoon Network, TBS and TNT are no longer be available.
ESPN2 HD, Freeform, Sundance , TLC, Universal HD, NBC Sports now added.

**Comment by lucasharding** [comment]
I just uploaded a new .ipa with new icons. You can either build from source or download the .ipa from https://github.com/lucasharding/antenna/releases/tag/1.0.2
